#!/bin/bash

main() {
	local container_id="$1"; shift
	local port="$1"; shift
	local path="$1"; shift
	local opts="$@"
	
	local ip="$(docker inspect -f "{{.NetworkSettings.IPAddress}}" $container_id)"
  if [[ "$ip" == "" ]]; then
    if [ ! -z "$HOSTIP" ]; then
      local ip="$HOSTIP"
    else
      local ip="$(hostname)"
    fi
  fi
	curl \
		--silent \
		--show-error \
		--fail \
		--dump-header /dev/stderr \
		--retry 2 \
		--max-time 10 \
		$opts \
		"http://$ip:$port$path" > /dev/null
}

main $@