#!/bin/bash

main() {
	local container_id="$1"; shift
	local port="$1"; shift # not used for now but kept for compatibility of gliderlabs/registrator
	local cmd="$@"
	echo "docker exec $container_id  $cmd"
	docker exec $container_id  $cmd
}

main $@
