#!/bin/bash

readonly IMAGE="wehkamp/blaze-container-consul"

main() {
	local container_id="$1"; shift
	local port="$1"; shift
	local path="$1"; shift
	local opts="$@"
	
	local ip="$(docker inspect -f "{{.NetworkSettings.IPAddress}}" $container_id)"
  if [[ "$ip" == "" ]]; then
          local ip="$(hostname)"
  fi
	local curl_cmd="curl \
		--silent \
		--show-error \
		--fail \
		--dump-header /dev/stderr \
		--retry 2 \
		--max-time 10 \
		$opts \
		\"http://$ip:$port$path\" > /dev/null"
  
	docker run --rm --net container:$container_id --entrypoint "/bin/bash" $IMAGE -c "$curl_cmd"
}

main $@